language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
before_script:
  - wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2
  - tar jxvf htslib-1.9.tar.bz2 
  - cd htslib-1.9 && make && export PATH=$PATH:$PWD && cd ..
  - wget https://github.com/arq5x/bedtools2/releases/download/v2.27.0/bedtools-2.27.0.tar.gz
  - tar zxvf bedtools-2.27.0.tar.gz
  - cd bedtools2 && make && export PATH=$PATH:$PWD/bin && cd ..
  - wget https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/archive/v1.1.tar.gz
  - tar zxvf v1.1.tar.gz 
  - cd Complete-Striped-Smith-Waterman-Library-1.1/src
  - gcc -Wall -O3 -pipe -fPIC -shared -rdynamic -o libssw.so ssw.c ssw.h
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD
  - cd ../..

  - pip install annot_utils==0.3.1
  - pip install pysam
  - pip install requests
  - pip install future
  - cat /etc/issue

script:
  - pip install .
  - python setup.py test 
